Initialized Cell and test
GDemps/BattleShip pull request #1
Opened 2020-03-24 03:38 UTC by GDemps

I just wanted to get the feel for the process, so check it out and make sure I spelled initialized correctly.  :)

2020-03-24 03:49 UTC, muydanny requested changes

2020-03-24 03:49 UTC, muydanny commented on test/Cell_test.rb
> +require "pry"
Great Grant! We can take this pry out  and binding.pry and we'll be good! Great way for me to learn how to comment lol

2020-03-24 04:08 UTC, muydanny requested changes

2020-03-24 04:08 UTC, muydanny commented on lib/Cell.rb
>  require 'pry'
Found another pry lol

2020-03-24 17:45 UTC, GDemps commented on lib/Cell.rb
>  require 'pry'
cool, I'll take it out

2020-03-25 01:30 UTC, muydanny approved these changes
Looks great partner!

2020-03-25 01:30 UTC, merged